# Generated by Django 3.2.20 on 2023-08-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playersapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='vehicle',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
