# Generated by Django 3.2.20 on 2023-08-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playersapp', '0003_alter_player_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='vehicle',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
