# Generated by Django 3.2.20 on 2023-08-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playersapp', '0004_alter_player_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='vehicle',
            field=models.UUIDField(),
        ),
    ]
